filters:
  naics_include:
    - "541715"
    - "541330"
    - "541511"
    - "541512"
  preferred_notice_types:
    - "Sources Sought"
    - "Request for Information"
    - "Combined Synopsis/Solicitation"
    - "Special Notice"
  exclude_notice_types:
    - "Award Notice"
  posted_from_days: 14

keywords:
  positive:
    prototype: 4
    experimentation: 4
    demonstration: 4
    r&d: 3
    research: 3
    sensing: 3
    sensor: 3
    autonomy: 3
    uas: 3
    uav: 3
    ugv: 3
    c-uas: 3
    counter uas: 3
    robotics: 3
    unmanned: 3
    ew: 2
    electronic warfare: 3
    isr: 2
    sigint: 2
    atak: 2
    edge: 2
    offline: 2
    austere: 2
    tactical: 2
    mesh: 2
  negative:
    construction: 5
    janitorial: 5
    grounds maintenance: 5
    facilities: 4
    office supplies: 4
    furniture: 4
    license renewal: 4
    reseller: 4

scoring:
  include_in_digest_score: 12
  naics_match_boost: 4
  notice_type_boost: 3
  set_aside_boost: 2
  deadline_urgency_boost: 2

digest:
  max_items: 30
